### ISSUE TITLE
Issue with pre-commit default hook

### ISSUE THREAD

**Issue by mattaltepeter** [whiteCcinn/husky-php#1]
I want to change the behavior of the `pre-commit` hook, but no matter what I put in my `.huskyrc` file, it always runs the default pre-commit script. 

I started digging into it and I think its due to this:
```
if (json_last_error() === JSON_ERROR_NONE) {
  $this->conf = array_merge($this->conf, $userConf);
}
```

The documentation states that the huskyrc file should look like this:
```
{
  "husky": {
    "hooks": {
      "post-merge": "composer install --no-dev",
      "pre-commit": "echo 'test'"
    }
  }
}
```

But the default is stored like this:
```
protected $conf = [
        'hooks' => [
            'pre-commit' => 'husky-default-pre-commit',
        ]
    ];
```

So the resulting array that the `RunServices::execute` method loops over looks like this:
```
Array
(
    [hooks] => Array
        (
            [pre-commit] => vendor/ccinn/husky-php/sh/husky-default-pre-commit
        )

    [husky] => Array
        (
            [hooks] => Array
                (
                    [post-merge] => composer install --no-dev
                    [pre-commit] => echo 'test'
                )

        )

)
```

I'm looking for clarification on which way is correct. If the documentation should just be updated or if we should fix the package

**Comment by whiteCcinn** [comment]
@mattaltepeter 
Normally, user behavior overrides the default behavior. If you tried and failed, there might be a bug. I'll try it later.Thanks for your feedback.

**Comment by mattaltepeter** [comment]
I was able to override it by switching the `.huskyrc` file to the following:
```
{
  "hooks": {
    "post-merge": "composer install --no-dev",
    "pre-commit": "echo 'test'"
  }
}
```

So I think its just the documentation problem in the readme
