### ISSUE TITLE
support symfony/filesystem 6

### ISSUE THREAD

**Issue by Stevie-Ray** [whiteCcinn/husky-php#10]
Im trying to use this package with Magento 2.4.5 but get the following error: 

` ccinn/husky-php v0.3.1 requires symfony/filesystem ^3.4|^4|^5 -> found symfony/filesystem[v3.4.0, ..., v3.4.47, v4.0.0, ..., v4.4.42, v5.0.0, ..., v5.4.13] but the package is fixed to v6.1.5 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.`

**Comment by Trusted97** [comment]
Hi @Stevie-Ray 
In this [release](https://github.com/whiteCcinn/husky-php/releases/tag/v0.3.2) we've add the support for symfony/filesystem 6.x

Good coding!
