### ISSUE TITLE
Library improvements

### ISSUE THREAD

**Issue by Trusted97** [whiteCcinn/husky-php#11]
Hello @whiteCcinn
Thanks for your amazing work! I have ideas on how to evolve and improve the library:

- Dockerized container with different versions of PHP 8.X
- Testing via PHPUnit
- CI/CD via Github Actions
- Symfony 6.x support
- Typing

Would you like to receive PR?

Best regards

**Comment by whiteCcinn** [comment]
@Trusted97 Of course, why not, welcome to submit your precious PR

**Comment by Trusted97** [comment]
Hi @whiteCcinn 

This is the first [PR](https://github.com/whiteCcinn/husky-php/pull/12) in this days if i'll able to found sometimes i'll add the other features 😄 

For now i'll close this issue 😄
