### ISSUE TITLE
Improve developer experience avoiding hard templ

### ISSUE THREAD

**Issue by Trusted97** [whiteCcinn/husky-php#21]
Hi @whiteCcinn 

I'm looking at this part of the [library](https://github.com/whiteCcinn/husky-php/blob/master/src/Util/Util.php#L188 ) and it's currently just a hardcoded sh script. how about if we replace it with a .tpl file? A bit like they are used in the Symfony [maker bundle](https://github.com/symfony/maker-bundle/blob/main/src/Resources/skeleton/controller/Controller.tpl.php).

WDYT?

**Comment by whiteCcinn** [comment]
I think 'sh scripts' can do a lot more than just PHP `.tpl` files. I don't think it's very different from today's scripts, or maybe I just don't understand what you're trying to do. 
@Trusted97
