### ISSUE TITLE
PHP 7.4 support

### ISSUE THREAD

**Issue by saskaak** [whiteCcinn/husky-php#5]
Using with PHP 7.4 produces the following message:

"PHP needs to be a minimum version of PHP 5.6.0 and maximum version of PHP 7.3.*."

**Comment by whiteCcinn** [comment]
I will organize it systematically in the near future @saskaak

**Comment by whiteCcinn** [comment]
@saskaak 

use https://github.com/whiteCcinn/husky-php/releases/tag/v0.2.0
